version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.micrometer:micrometer-registry-prometheus
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: io.micrometer:micrometer-core
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: org.apache.camel:camel-test-spring
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-jackson
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-caffeine
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-servlet
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-base64
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-zipfile
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-zipkin
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-micrometer
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-mail
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-jaxb
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel:camel-spring-ws
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.apache.camel.springboot:camel-spring-boot-starter
    versions:
    - 3.7.1
    - 3.7.2
    - 3.8.0
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR10
    - Hoxton.SR9
  - dependency-name: org.webjars:bootstrap
    versions:
    - 4.6.0
  - dependency-name: org.codehaus.groovy:groovy-json
    versions:
    - 3.0.7
  - dependency-name: org.codehaus.groovy:groovy-xml
    versions:
    - 3.0.7
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.2
    - 2.3.0
    - 2.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
- package-ecosystem: gradle
  directory: "/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 50
